prefix category: <http://ldp.com/spot/category/>
prefix user:  <http://ldp.com/data/user/>

prefix type: <http://ldp.com/spot/category/type/>
prefix group: <http://ldp.com/spot/category/group/>
prefix for: <http://ldp.com/spot/category/for/>
prefix spot_name: <http://ldp.com/spot/spot_name/>

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

prefix province: <http://www.province.com/>


SELECT *
WHERE {

  ?subject ?p ?object.
}
LIMIT 25
